add_rules("mode.debug", "mode.release")
add_requires("dtkcore", "dtkgui", "dtkwidget","qt5widgets","Qt5QuickControls2",{ system = true})

rule("example-deps")
    add_deps("dpalette")

target("example-cpp")
    add_packages("dtkcore","dtkgui","dtkwidget","qt5widgets","Qt5QuickControls2")
    add_rules("example-deps")
    add_rules("qt.quickapp")
    add_files("cpp/**.cpp")
    add_files("*.qrc")
    add_files("dtk/include/*.cpp|h")
    add_includedirs("dtk/include")

target("example-python")
    set_kind("phony")
    add_deps("dpalette")--("example-deps")
    on_run(function(target)
        os.cd('examples')
        local targetdir=path.join(os.projectdir(),path.directory(target:dep("dpalette"):get("targetdir")))
        os.setenv("QML2_IMPORT_PATH",targetdir)
        print('targetdir',targetdir,'import path',os.getenv("QML2_IMPORT_PATH"))
        os.execv("python",{"python/main.py"})
        -- os.execv("env",{envs={PATH="ABCD;aa"}})
    end)